### ISSUE TITLE
Nativescript 3.0 not compatible

### ISSUE THREAD

**Issue by marcbuils** [NativeScript/nativescript-googlemaps#9]
Hello,

The project use "ui/proxy", but this one is removed from nativescript 3.0.

**Comment by NickIliev** [comment]
@marcbuils use the [master branch](https://github.com/NativeScript/nativescript-googlemaps/tree/master/src) for your NativeScript 3.0.0 projects.

[The latest plugin version in NPM](https://www.npmjs.com/package/nativescript-googlemaps) is also 3..0.0 compatible

**Comment by marcbuils** [comment]
Hi NickIliev,
Sorry, I don't know why, but I don't seen that the master branch was updated.

Thanks
